version: '3.8'

networks:
  k6:
  grafana:
  influxdb:

services:
  influxdb:
    image: influxdb:latest
    networks:
      - k6
      - grafana
      - influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=QA24
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=QADB
      - DOCKER_INFLUXDB_INIT_BUCKET=k6metric
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=XTjiXgy_mxfuhhd0adSq5qSPz03vX-pNaZgzqiqq5AqrDPjc_b1suV73MxxGL0EvLBmGBW6kzcb8x27WxTAh8Q==
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:8.2.6
    networks:
      - grafana
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  influxdb-data:
  grafana-data: